### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by mvhulten** [CNugteren/NLWeer#1]
Vooralsnog is het programma niet beschikbaar in F-Droid; althans, ik kan hem niet vinden onder de naam `NLWeer`.

Ik kijk uit naar het gebruiken van deze veelbelovende app!

**Comment by PanderMusubi** [comment]
Same here. If you need help getting this app published on Android and/or adding a badge 'get it on F-Droid' in your readme, let me know.

**Comment by CNugteren** [comment]
I've made a request already 3 weeks ago but it takes a while apparently:
https://gitlab.com/fdroid/fdroiddata/merge_requests/5886

**Comment by CNugteren** [comment]
It is available in f-droid now:
https://f-droid.org/en/packages/foss.cnugteren.nlweer/
I've updated the README accordingly.
