### ISSUE TITLE
Error Neerslagverwachting

### ISSUE THREAD

**Issue by EJH83** [CNugteren/NLWeer#14]
Hoi Cedric,

Leuke app, mis alleen nog een widget met de regenverwachting ;)

bij het laden van de "Neerslagverwachting" krijg ik de melding:
Data kon niet geladen worden (locatie buiten Nederland?). 

Blijf deze melding houden, ondanks meerdere keren herladen i.c.m. aanpassingen in de instellingen. Alle andere opties werken wel goed. Locatie: Kloetinge. Appversie 1.3.0.

**Comment by CNugteren** [comment]
> Leuke app, mis alleen nog een widget met de regenverwachting ;)

Bedankt! Bedoel je de Buiendar 2 uur vooruit pagina bijvoorbeeld? De bedoeling is om een volgende update het zo te maken dat er door de gebruiker andere kaarten toegevoegd kunnen worden.

> bij het laden van de "Neerslagverwachting" krijg ik de melding:
Data kon niet geladen worden (locatie buiten Nederland?).

Die melding komt zodra er geen data terug komt van de Buienradar GPS gadget. Hier is een voorbeeld van een geldige query voor in de buurt van Kloetinge, dat lijkt wel te werken:
https://gpsgadget.buienradar.nl/data/raintext?lat=51.49&lon=3.88
Je zou eens kunnen proberen om handmatig die coordinaten in te stellen als locatie? Of eventueel een andere locatie in stellen - werkt het dan wel? En wordt de rode cirkel wel goed weergegeven op de kaarten?

**Comment by CNugteren** [comment]
(using English to make this a bit more useful for others perhaps)

The just released 1.4.0 version (within a few days on F-Droid) now makes debugging this a bit easier:
* It will first check if lon/lat are available at all, e.g. location might not be enabled or available
* Then it will check if the lon/lat values are within the bounds of the acceptable range by Buienradar (basically the Netherlands and a bit around it)
* Only then it will query the Buienradar API. If it still fails it will display the coordinates it tried to fetch. You can then use that to query directly afterwards in the same browser the URL (e.g. https://gpsgadget.buienradar.nl/data/raintext?lat=51.49&lon=3.88) and see if perhaps the Buienradar website has issues or you device can't connect to the internet.

Do let me know if you still suffer from this issue and whether the 1.4.0 update helps debug the cause.

**Comment by EJH83** [comment]
Hoi Cedric,

Krijg de API niet geïnstalleerd vanaf GitHub, zie printscreen (ondanks legitieme app toekenning voor installaties). Wacht wel tot hij op Fdroid staat. Laat je het resultaat weten.

Groeten,

Eric[Image]



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CNugteren** [comment]
Any update on this @EJH83? Do you still experience this issue?

**Comment by EJH83** [comment]
No, everything works fine at the moment. Kind regards.

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________
