### ISSUE TITLE
Include hail radar in buienradar

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#17]
Plesae, include hail radar in buienradar as this information can prevent a lot of damage

https://www.buienradar.nl/nederland/neerslag/hagelradar

**Comment by CNugteren** [comment]
This is already available in NLWeer. Make sure you have the latest version (1.4.0) and that you have enabled this map specifically in the settings.

**Comment by PanderMusubi** [comment]
They don't show up in that version via F-Droid. Perhaps something went wrong with the version when building or publishing.

![Screenshot_20200814-224543_NLWeer](https://user-images.githubusercontent.com/198964/90291398-2075e980-de80-11ea-8ba0-2e790423d66a.png)

![Screenshot_20200814-224556_NLWeer](https://user-images.githubusercontent.com/198964/90291402-21a71680-de80-11ea-880c-342e4fb382b6.png)

**Comment by CNugteren** [comment]
But have you checked the settings like I said? You have to enable this map.

**Comment by PanderMusubi** [comment]
Yes, found it. Need explicit activation. Thanks.
