### ISSUE TITLE
Add feature graphic

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#2]
Please add a feature graphic to metadata/en-US/ so that the F-Droid client can show this.

**Comment by CNugteren** [comment]
Could you clarify what a feature graphic is exactly? I'm not too familiar with this. When I look on [F-Droid](https://f-droid.org/packages/foss.cnugteren.nlweer/) it does display screenshots, but that's not what you mean I guess?

**Comment by PanderMusubi** [comment]
These are not shown on the website, only inside F-Droid apps. See for example https://github.com/zamojski/TowerCollector/blob/master/fastlane/metadata/android/en-US/images/featureGraphic.png and https://github.com/y20k/transistor/blob/master/metadata/en-US/images/featureGraphic.png (see also these apps and e.g. the app Etar in the F-Droid app)

**Comment by CNugteren** [comment]
I've added a feature graphic, here is the English version for example:
https://github.com/CNugteren/NLWeer/blob/master/metadata/en-US/images/featureGraphic.png
