### ISSUE TITLE
Darkmode for rain prediction chart

### ISSUE THREAD

**Issue by bitpixl** [CNugteren/NLWeer#30]
Is there maybe a way to have the rain prediction chart also respect the (system) darkmode setting?
I'm using LineageOS 17 with darkmode enabled on the phone and on NLWeer, but the rain prediction chart still shows up  white.

thank you for reading and keep up the great work!

**Comment by CNugteren** [comment]
Thank you for your input. Actually, the app already has a setting to set the background colour of the regular maps to either black or white (default). Would it work for you if I use that same setting to also set the background colour of the graph (making sure the text is still readable of course)?

**Comment by bitpixl** [comment]
Yeah that would be great!

**Comment by CNugteren** [comment]
I've decided to anyway make a proper 'dark-mode' button that also affects the settings screen, the menu bar, and the weather report, as well as the rain prediction chart. The background colour option is still there, and only affects the background of the various maps.

The rain chart in dark mode:
![Screenshot_1612382842](https://user-images.githubusercontent.com/1162108/106803454-88a1cd00-6664-11eb-9ef2-1a5267eead8a.png)

The dark mode option button:
![Screenshot_1612382876](https://user-images.githubusercontent.com/1162108/106803456-893a6380-6664-11eb-9805-5df08d253be7.png)

See https://github.com/CNugteren/NLWeer/pull/31

I'll be testing this a little while on device and afterwards will make a new release. Let me know if you have any comments/suggestions still.

**Comment by bitpixl** [comment]
That looks really slick!

The only you could maybe add as I've seen this in multiple apps is a true "amoled" pitchblack mode, but as far I'm concerned it's not really needed :)

**Comment by CNugteren** [comment]
Would be nice indeed, but I've implemented this dark mode based on [Android's dark theme](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme), so I didn't actually set the colours everywhere, it is done automatically. Creating a true black mode would require different code, so that is significant effort. Since I don't expect users to look at NLWeer for hours per day, I would say it is good enough the way it is now :-)

**Comment by bitpixl** [comment]
The new darkmode looks great! thanks for implementing it!
