### ISSUE TITLE
Add buienradar 3-hour forecast radar

### ISSUE THREAD

**Issue by Lee245** [CNugteren/NLWeer#34]
As a feature request, I would like to have the buienradar 3-hour forecast (https://www.buienradar.nl/nederland/neerslag/buienradar/3uurs) included in the app. This makes it much easier to see when it's safe to go outside :).

**Comment by CNugteren** [comment]
Thanks for your request. Indeed, it would be a good addition.

However, unfortunately that image is not a `.git` but instead a sequence of images: https://image-cdn.buienradar.nl/br-processing/image-api/RadarMapRainNL/Sprite/202103151915__550x512_False_False_True_0_18_1_0_run202103151905.png. Furthermore, it has the current time and date in its name. So unless you can find a fixed link to a .gif like [this one](https://api.buienradar.nl/image/1.0/RadarMapNL?w=550&h=510), it will be a bit more effort to add it. Which is the reason I did not add it in the past, but if I spend some time I could try and see if I can make it work.

**Comment by Lee245** [comment]
Thanks for considering taking up both of my feature requests. Both indeed seem to be a bit of work to fit into the current app. 

I may try looking into my feature requests myself, although Andorid development is new to me so it may take some time to get up to speed.

**Comment by CNugteren** [comment]
If you decide to work on it, I can try to guide you a bit. I think your feature requests would be implemented in a very similar way to the way the 'pluim' graph is implemented. So you could try to do more or less the same as in [this commit](https://github.com/CNugteren/NLWeer/pull/29/commits/5b25a47d215bc89666b4fef3aebf902716c62823) but then with other content/names.

**Comment by Lee245** [comment]
Thanks for the suggestion. As you undoubtedly recognize, time is the limiting factor for me, but I'll certainly have a look to see how I can implement it. First I want to get more familiar with the android development basics, so it may take a while... Thanks for the offer! I'll let you know if I need more guidance.

**Comment by Lee245** [comment]
The KNMI neerslagradar has recently been updated to also include a ~1.5 hour forecast, so as far as I'm concerned this ticket can be closed.
