### ISSUE TITLE
Add visualization of 6-day forecast

### ISSUE THREAD

**Issue by Lee245** [CNugteren/NLWeer#35]
On the KNMI web page (https://knmi.nl/nederland-nu/weer/verwachtingen), you can find a very nice visualization of the 6-day forecast (as now displayed in the 'Vooruitzichten" section of the "Weerbericht" tab). A visualization instead of raw text will be a great improvement to the page.

This is hot it is shown on the KNMI web page:
![KNMI_6dayForecast](https://user-images.githubusercontent.com/7467080/111066895-ac58fe00-84c1-11eb-9f97-afa015e4d47e.png)

A transposed view of this table would fit in perfectly.

@CNugteren And I forgot to mention that I really enjoy using the NLWeer app. Thank you for providing an open-source weather app :+1:

**Comment by CNugteren** [comment]
Good to hear you like it :-)

Yes that would be a useful addition. However, as you most likely saw this is not an image but HTML, so it will take a bit more effort to get it in (and to make it look good). I'll put it on the todo-list to have a look for when I have time.

**Comment by Lee245** [comment]
It's been a while and I'm still using this ap on a daily basis :). I looked into this and I just hacked the 6-day forecast into the app using WebView. It currently looks like this:

![Screenshot_20240211-201013_NLWeer](https://github.com/CNugteren/NLWeer/assets/7467080/22c1cbae-4dc8-45e1-93ae-e2b63780c4ff)

What do you think about having this on a separate frame and taking it out of the weather report? Of course, I would still need to add something to make it clear you can scroll horizontally, and deal with dark theme and translations. Let me know what you think or if you have other ideas.

**Comment by CNugteren** [comment]
Yes that would be a great addition to the app. I see you already made a draft PR :+1: I don't have much time this week so it will take a little bit more time before I can take a look at it.

**Comment by Lee245** [comment]
Perfect! I'm still fiddling with some details (scroll bar, vertical alignment and dark mode). When I'm done I'll publish the PR for review.

As a side note, I may do some more work after this. Pluim seems to have some bugs currently, and I may also work on upgrading dependencies and perhaps the 3-hour buienradar. Just so you know what may be coming, depending on the time I have.
