### ISSUE TITLE
Feature request: add KNMI satellite imagery.

### ISSUE THREAD

**Issue by bodypilot** [CNugteren/NLWeer#36]
This would be a cool addition: 
https://www.knmi.nl/nederland-nu/weer/actueel-weer/satellietbeeldenloop

If animated GIFs don't work in this app, this single image could be an alternative:
https://www.knmi.nl/nederland-nu/weer/actueel-weer/satellietbeelden

**Comment by CNugteren** [comment]
Thanks for the suggestion. Yes, I think it should be possible to just use the animated gif.

I don't have much time these days but if I can find an hour or so I'll look at this :+1:

**Comment by CNugteren** [comment]
This has been added in https://github.com/CNugteren/NLWeer/pull/37. It will be part of the next release of the app.
