### ISSUE TITLE
NLTraffic app

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#4]
Please offer another app (or include in this app) maps of traffic conditions in the Netherlands for roads and railways such as:
- https://www.verkeerplaza.nl/ (see also submaps via http://file.nl )
- http://anwb.nl such as https://www.anwb.nl/binaries/content/gallery/anwb/portal/verkeer/nederland/verkeer-home-entree/anwb-verkeersverwachting-1520-x-855.jpg/anwb-verkeersverwachting-1520-x-855.jpg/anwb%3Aw1520 and other submaps
- https://www.ns.nl/reisinformatie/actuele-situatie-op-het-spoor

(Some maps are made of a background map with a transparent overlay. These can also be used as such in Android.)

**Comment by PanderMusubi** [comment]
https://www.anwb.nl/verkeer/nederland/verkeersinformatie/dagelijkse-drukke-trajecten

**Comment by PanderMusubi** [comment]
https://www.anwb.nl/verkeer/nederland/verkeersverwachting

**Comment by PanderMusubi** [comment]
https://rijkswaterstaatverkeersinformatie.nl/kaart.html (probably a challenge to render )

https://rijkswaterstaatverkeersinformatie.nl/statistiek.html (two gifs to be placed one above the other)

**Comment by CNugteren** [comment]
Sorry, I have to close this request, since this is a weather app, and I'm not planning on developing a traffic app. Perhaps someone else can pick this up.
