### ISSUE TITLE
Add pollennieuws

### ISSUE THREAD

**Issue by peter-scholtens** [CNugteren/NLWeer#41]
With the current dry weather in the Netherlands, a lot people of suffer from hay fever. Including this [map](https://pollennieuws.nl/weerkaart/KaartNL_280-website.png) could make sense.

**Comment by CNugteren** [comment]
Note that this map is not from KNMI but from another website. I could not find any information about copyright or permissions to embed these images in other products. Did you find anything like that?

**Comment by peter-scholtens** [comment]
There is a [EULA-like](https://pollennieuws.nl/achtergrond/gebruiksvoorwaarden/) phrase like:

> De informatie mag uitsluitend door u worden gebruikt. U mag de informatie niet overdragen, verveelvoudigen, bewerken of verspreiden.

But I would advice to ask but I would advice to ask either via the [contact page](https://pollennieuws.nl/achtergrond/contact/), [e-mail](mailto:info@pollennieuws.nl) or phone, as you share the same interest: informing the general public in the best possible way.

**Comment by CNugteren** [comment]
Could you maybe ask this since you are interested? And if they respond positively, I'll add this map to the app.

**Comment by peter-scholtens** [comment]
Site owner doesn't want to release this information under a Creative Commons License or alike.
