### ISSUE TITLE
Offer option to change language

### ISSUE THREAD

**Issue by PanderMusubi** [CNugteren/NLWeer#5]
Offer option to choose language other than the system default. Menu items would be:
- system language
- Dutch
- English

Or when using the app in Dutch:
- systeemtaal
- Nederlands
- Engels

Language codes supported: '' (default = system language), 'nl', 'en'

When desired, I can provide German translation.

**Comment by CNugteren** [comment]
I'm wondering why anyone would want such a feature? Could you please elaborate? Currently the app displays in the system language indeed, which should be fine. I don't think it is worth investing time in this.

If you want a German locale, please feel free to make a PR with the relevant files (strings.xml and the metadata files).

**Comment by PanderMusubi** [comment]
I am living in the Netherlands but my smartphone is set to English as I use most apps in English. The exception to that is apps that only relate to where I live, such as garbage collection information and weather forecasts, since having this kind of Dutch content in an English app is a bit wierd. For that, I use settings in those apps to not use the language my system is set to, but I manually choose Dutch.

**Comment by CNugteren** [comment]
It has been a while, but I've made an (unsuccessful) attempt at implementing this. Based on [this suggestion](https://stackoverflow.com/questions/50785840/change-locale-programmatically-in-kotlin) I've implemented this https://github.com/CNugteren/NLWeer/compare/language_selection?expand=1, but I'm running into two issues:
1. The language actually doesn't change, even when restarting the app. I have verified that the new code is being called with the right 'language' value, but nothing happens.
2. When changing the preference value, ideally a manual re-start of the app is not needed. Instead, the activity can be restarted programmatically, but that crashes.

**Comment by CNugteren** [comment]
I finally got it working now, it is merged into master here:
https://github.com/CNugteren/NLWeer/pull/20

I'll do some more on-device testing and soon will release a new version of the app.

Feel free to add a German locale in the meantime. The only real task is to translate this file:
https://github.com/CNugteren/NLWeer/blob/master/app/src/main/res/values/strings.xml
Other than that there are just some minor modifications needed, but I can do that for you. The thing I can't do is the German part :-)

**Comment by CNugteren** [comment]
Closing this since it is in master and in the just released v1.5.0 version. It takes a few days before it shows up on F-Droid.
