### ISSUE TITLE
F-Droid build fails

### ISSUE THREAD

**Issue by Lee245** [CNugteren/NLWeer#50]
F-Droid build fails for v1.10 (https://gitlab.com/fdroid/fdroiddata/-/commit/82be46139adc7df8d615ed86f5098c34f8589033). You need to add installing JDK 17 to the metadata file as explained here: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/

(See Build Environment section)

**Comment by CNugteren** [comment]
I tried to make the changes myself yesterday but ran into errors when creating the merge request, my guess was that my fork was too old. So today I removed the fork and started again, but then I found that someone else fixed the issue 7 hours ago:
https://gitlab.com/fdroid/fdroiddata/-/commit/ef8b699825521a352a1f9c4cf18ec27f1365178b.

So my guess is that soon a new build will made and it will work.

**Comment by Lee245** [comment]
Perfect! Thanks for having a look :) I will close the issue then.
