### ISSUE TITLE
6-day forecast broken

### ISSUE THREAD

**Issue by fincentxyz** [CNugteren/NLWeer#54]
The 6-day weather forecast once again is not able to load the data.

**Comment by CNugteren** [comment]
Are you using version 1.10.1 or 1.10.2? Because this might have already been fixed in https://github.com/CNugteren/NLWeer/pull/53.

**Comment by fincentxyz** [comment]
> Are you using version 1.10.1 or 1.10.2? Because this might have already been fixed in #53.

Excuses, ik zag inderdaad net pas dat 1.10.2 laatst is uitgebracht. F-Droid ziet die versie alleen nog niet, ik moet nog even geduld hebben. Bedankt voor het oplossen!
