### ISSUE TITLE
Allow swiping left/right to change maps

### ISSUE THREAD

**Issue by andswitch** [CNugteren/NLWeer#8]
If you want to quickly go through all the maps, the menu navigation is a bit suboptimal. It would be easier if you could swipe left/right in that case.

**Comment by CNugteren** [comment]
I've implemented something in the `swipe_left_right` branch (see https://github.com/CNugteren/NLWeer/compare/swipe_left_right) but I'm not overly happy. Two things:
* On the left is already the menu as well, so the two might get confused
* The implementation I have so far of detection a left/right swipe doesn't feel natural yet, swiping is too difficult at the moment it feels.

If you want, you can have a try as well and tell me what you think.

**Comment by andswitch** [comment]
I agree that it doesn't feel right, and it indeed interferes with the menu. It also feels like it takes too much effort to make the swiping gesture work.

**Comment by CNugteren** [comment]
I'm closing this since the idea didn't really work out nicely, and since the same high-level issue of quick navigation is also discussed (and a solution implemented) in #15.
