### ISSUE TITLE
Add longer term forecasts

### ISSUE THREAD

**Issue by andswitch** [CNugteren/NLWeer#9]
If this app included the 5-day forecast and long-term forecast, I would probably never have to visit knmi.nl again.

**Comment by CNugteren** [comment]
I like this idea, however I don't know of any API to get this information. For the images I can just display those images in the app, but for text it becomes more problematic to only display particular text without the rest of the HTML on e.g. this page: https://www.knmi.nl/nederland-nu/weer/verwachtingen

I actually thought of instead using [OpenWeatherMap](https://openweathermap.org/city/2759794), which does have a nice API to retrieve particular kinds of data. But it doesn't have the quality of the KNMI website, so if anyone has an idea of how to retrieve just the weather report and/or the forecast, then please let me know.

**Comment by andswitch** [comment]
I couldn't quickly find an API for the KNMI data either. You can convert the HTML of the forecasts page to plaintext using the program `w3m`, and it will give you the 5-day forecast data in a more parser-friendly format [1]. Maybe there are libraries available for Android that can do something similar? Apparently there is a `fromHtml` method that looks like it could do it: https://stackoverflow.com/questions/22573319/how-to-convert-html-text-to-plain-text-in-android.

[1] `w3m -cols 500 -dump https://www.knmi.nl/nederland-nu/weer/verwachtingen | tail -n +46 | head -n -24`

```
Vandaag & morgen

Vandaag en morgen zeer zacht, vooral vrijdag ook regen en veel wind

Vannacht is er weinig bewolking en het blijft overal droog. De temperatuur varieert van 4°C in het noordoosten tot 9°C in het uiterste zuiden. Er staat een matige zuidoostenwind, aan de kust en boven het IJsselmeer is de wind vrij krachtig tot krachtig, 5 tot 6 Bft.

Overdag is het droog en is er volop ruimte voor de zon. In de loop van de middag neemt in het westen de bewolking toe en tegen de avond kan daar mogelijk wat lichte regen vallen. Het wordt zeer zacht met maxima die uiteenlopen van 11°C op de Wadden tot lokaal 15°C in Limburg. De zuidoostenwind is matig, aan zee en op het IJsselmeer vrij krachtig, in de avond mogelijk weer krachtig.

In de nacht van donderdag op vrijdag zijn er in het oosten opklaringen. In het westen is er meer bewolking aanwezig en langs de westkust kan lichte regen vallen. Ook de nacht verloopt erg zacht met minima van 7°C in het noordoosten tot 11°C in het zuidwesten. De zuidoostenwind is matig, aan zee en boven het IJsselmeer vrij krachtig.

Vrijdag overdag raakt het overal bewolkt en van het zuidwesten uit volgt er af en toe regen. In het loop van de middag trekt de regen naar het noordoosten weg. Er volgen dan ook enkele opklaringen maar een bui blijft mogelijk. Het wordt opnieuw zacht met maxima rond 13°C. De wind komt eerst uit het zuidoosten neemt toe naar matig tot vrij krachtig, aan zee en boven het IJsselmeer naar vrij krachtig tot krachtig. In de middag draait de wind naar zuid tot zuidwest en kan dan in de kustgebieden
toenemen naar hard, mogelijk stormachtig, 7 tot 8 Bft. Langs de westkust zijn er dan windstoten mogelijk tot ca. 75 km/uur. (Bron: KNMI)

19/12/2019 00.57 uur LT

Vooruitzichten

Wisselvallig en vrij zacht met van tijd tot tijd regen. Tijdens de Kerstdagen wordt het mogelijk droger met meer zon.

19/12/2019 03.51 uur LT
Scroll onderstaande tabel om meer te zien

  • Vr 20-12-2019 [2-druppels] Max. 13° Min. 9° Neerslag 2/5mm Neerslagkans 80% Zonneschijn 10% Windkracht Z 5
  • Za 21-12-2019 [1-druppel-] Max. 8/9° Min. 5/7° Neerslag 0/2mm Neerslagkans 60% Zonneschijn 20% Windkracht Z 4
  • Zo 22-12-2019 [2-druppels] Max. 8° Min. 5/6° Neerslag 2/6mm Neerslagkans 80% Zonneschijn 10% Windkracht W 4
  • Ma 23-12-2019 [2-druppels] Max. 7/8° Min. 4/6° Neerslag 1/5mm Neerslagkans 70% Zonneschijn 20% Windkracht ZW 4
  • Di 24-12-2019 [2-druppels] Max. 7/8° Min. 4/6° Neerslag 1/3mm Neerslagkans 50% Zonneschijn 20% Windkracht W 4
  • Wo 25-12-2019 [1-druppel-] Max. 7/8° Min. 3/5° Neerslag 0/1mm Neerslagkans 50% Zonneschijn 70% Windkracht W 3

19/12/2019 00.57 uur LT

Vooruitzichten lange termijn

donderdag 26 december tot en met donderdag 02 januari Aanvankelijk grote kans (ca. 70%) op een rustig en meest droog weertype, later weer toenemende kans op regen. De temperatuur ligt waarschijnlijk (iets) boven het langjarig gemiddelde. De kans op een kouder weertype met lichte vorst in de nacht en ochtend bedraagt ca. 30%.

19/12/2019 03.51 uur LT
```

**Comment by CNugteren** [comment]
I guess something like this could work:
https://softwarelogy.com/html-parse-in-kotlin-with-jsoup/
I'll have a go soon

**Comment by CNugteren** [comment]
I found some time to work on this and managed to parse the textual predictions as follows:
![weather_report](https://user-images.githubusercontent.com/1162108/72687606-d69e6e00-3aff-11ea-926e-ed198d050b7d.png)
What do you think? Should I have a look at the weather table as well, or is the text itself sufficient? Of course, when the KNMI changes their HTML layout this will break...

**Comment by CNugteren** [comment]
Actually I've also added the data from the table. I've merged this into master, and I'll work towards a new release of the app!

**Comment by andswitch** [comment]
Nice! Looking forward to it. Mainly the table is the interesting part actually.

**Comment by CNugteren** [comment]
A new version was released, see https://github.com/CNugteren/NLWeer/releases

And see here what it looks like: https://github.com/CNugteren/NLWeer/blob/master/metadata/en-US/images/phoneScreenshots/weather_report.png
